// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public interface CompanyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Company)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string companyName = 2;</code>
   */
  java.lang.String getCompanyName();
  /**
   * <code>string companyName = 2;</code>
   */
  com.google.protobuf.ByteString
      getCompanyNameBytes();

  /**
   * <code>double priceNow = 3;</code>
   */
  double getPriceNow();

  /**
   * <code>double priceMorning = 4;</code>
   */
  double getPriceMorning();

  /**
   * <code>double change = 5;</code>
   */
  double getChange();

  /**
   * <code>.google.protobuf.Timestamp date = 6;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 6;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();
}
