// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nesto = 1;</code>
   */
  java.lang.String getNesto();
  /**
   * <code>string nesto = 1;</code>
   */
  com.google.protobuf.ByteString
      getNestoBytes();
}
