// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double price = 2;</code>
   */
  double getPrice();

  /**
   * <code>int32 quantity = 3;</code>
   */
  int getQuantity();

  /**
   * <code>string idClient = 4;</code>
   */
  java.lang.String getIdClient();
  /**
   * <code>string idClient = 4;</code>
   */
  com.google.protobuf.ByteString
      getIdClientBytes();

  /**
   * <code>bool ask = 5;</code>
   */
  boolean getAsk();
}
