// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public interface SellOrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SellOrder)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double price = 2;</code>
   */
  double getPrice();

  /**
   * <code>int32 quantity = 3;</code>
   */
  int getQuantity();

  /**
   * <code>string clientID = 4;</code>
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 4;</code>
   */
  com.google.protobuf.ByteString
      getClientIDBytes();
}
