// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public interface StockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();

  /**
   * <code>string clientID = 3;</code>
   */
  java.lang.String getClientID();
  /**
   * <code>string clientID = 3;</code>
   */
  com.google.protobuf.ByteString
      getClientIDBytes();
}
