// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public final class StockEx {
  private StockEx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Company_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Company_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SellOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SellOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuyOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeHistoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstockEx.proto\032\037google/protobuf/timesta" +
      "mp.proto\"\026\n\005Empty\022\r\n\005nesto\030\001 \001(\t\"\220\001\n\007Com" +
      "pany\022\016\n\006symbol\030\001 \001(\t\022\023\n\013companyName\030\002 \001(" +
      "\t\022\020\n\010priceNow\030\003 \001(\001\022\024\n\014priceMorning\030\004 \001(" +
      "\001\022\016\n\006change\030\005 \001(\001\022(\n\004date\030\006 \001(\0132\032.google" +
      ".protobuf.Timestamp\"B\n\014StockRequest\022\016\n\006s" +
      "ymbol\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\022\020\n\010clientI" +
      "D\030\003 \001(\t\"N\n\tSellOrder\022\016\n\006symbol\030\001 \001(\t\022\r\n\005" +
      "price\030\002 \001(\001\022\020\n\010quantity\030\003 \001(\005\022\020\n\010clientI" +
      "D\030\004 \001(\t\"M\n\010BuyOrder\022\016\n\006symbol\030\001 \001(\t\022\r\n\005p" +
      "rice\030\002 \001(\001\022\020\n\010quantity\030\003 \001(\005\022\020\n\010clientID" +
      "\030\004 \001(\t\"^\n\014OrderRequest\022\016\n\006symbol\030\001 \001(\t\022\r" +
      "\n\005price\030\002 \001(\001\022\020\n\010quantity\030\003 \001(\005\022\020\n\010idCli" +
      "ent\030\004 \001(\t\022\013\n\003ask\030\005 \001(\010\"!\n\rOrderResponse\022" +
      "\020\n\010response\030\001 \001(\t\"O\n\023TradeHistoryRequest" +
      "\022\016\n\006symbol\030\001 \001(\t\022(\n\004date\030\002 \001(\0132\032.google." +
      "protobuf.Timestamp\"\211\001\n\024TradeHistoryRespo" +
      "nse\022\016\n\006symbol\030\001 \001(\t\022\r\n\005price\030\002 \001(\001\022\020\n\010qu" +
      "antity\030\003 \001(\005\022-\n\ttimestamp\030\004 \001(\0132\032.google" +
      ".protobuf.Timestamp\022\021\n\tbuyOrSell\030\005 \001(\0102\344" +
      "\001\n\rStocksService\022%\n\017getAllCompanies\022\006.Em" +
      "pty\032\010.Company0\001\022\"\n\003Ask\022\r.StockRequest\032\n." +
      "SellOrder0\001\022!\n\003Bid\022\r.StockRequest\032\t.BuyO" +
      "rder0\001\022&\n\005Order\022\r.OrderRequest\032\016.OrderRe" +
      "sponse\022=\n\014tradeHistory\022\024.TradeHistoryReq" +
      "uest\032\025.TradeHistoryResponse0\001B\024\n\020org.exa" +
      "mple.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { "Nesto", });
    internal_static_Company_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Company_descriptor,
        new java.lang.String[] { "Symbol", "CompanyName", "PriceNow", "PriceMorning", "Change", "Date", });
    internal_static_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockRequest_descriptor,
        new java.lang.String[] { "Symbol", "Quantity", "ClientID", });
    internal_static_SellOrder_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SellOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SellOrder_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "ClientID", });
    internal_static_BuyOrder_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BuyOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuyOrder_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "ClientID", });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "IdClient", "Ask", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_TradeHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_TradeHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeHistoryRequest_descriptor,
        new java.lang.String[] { "Symbol", "Date", });
    internal_static_TradeHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_TradeHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeHistoryResponse_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "Timestamp", "BuyOrSell", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
