// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public final class StockEx {
  private StockEx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Company_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Company_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SellOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SellOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyOrder_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuyOrder_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeHistoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstockEx.proto\032\037google/protobuf/timesta" +
      "mp.proto\"\026\n\005Empty\022\r\n\005nesto\030\001 \001(\t\"\220\001\n\007Com" +
      "pany\022\016\n\006symbol\030\001 \001(\t\022\023\n\013companyName\030\002 \001(" +
      "\t\022\020\n\010priceNow\030\003 \001(\001\022\024\n\014priceMorning\030\004 \001(" +
      "\001\022\016\n\006change\030\005 \001(\001\022(\n\004date\030\006 \001(\0132\032.google" +
      ".protobuf.Timestamp\"0\n\014StockRequest\022\016\n\006s" +
      "ymbol\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\"<\n\tSellOrd" +
      "er\022\016\n\006symbol\030\001 \001(\t\022\r\n\005price\030\002 \001(\001\022\020\n\010qua" +
      "ntity\030\003 \001(\005\";\n\010BuyOrder\022\016\n\006symbol\030\001 \001(\t\022" +
      "\r\n\005price\030\002 \001(\001\022\020\n\010quantity\030\003 \001(\005\"^\n\014Orde" +
      "rRequest\022\016\n\006symbol\030\001 \001(\t\022\r\n\005price\030\002 \001(\001\022" +
      "\020\n\010quantity\030\003 \001(\005\022\020\n\010idClient\030\004 \001(\t\022\013\n\003a" +
      "sk\030\005 \001(\010\"!\n\rOrderResponse\022\020\n\010response\030\001 " +
      "\001(\t\"O\n\023TradeHistoryRequest\022\016\n\006symbol\030\001 \001" +
      "(\t\022(\n\004date\030\002 \001(\0132\032.google.protobuf.Times" +
      "tamp\"\211\001\n\024TradeHistoryResponse\022\016\n\006symbol\030" +
      "\001 \001(\t\022\r\n\005price\030\002 \001(\001\022\020\n\010quantity\030\003 \001(\005\022-" +
      "\n\ttimestamp\030\004 \001(\0132\032.google.protobuf.Time" +
      "stamp\022\021\n\tbuyOrSell\030\005 \001(\0102\344\001\n\rStocksServi" +
      "ce\022%\n\017getAllCompanies\022\006.Empty\032\010.Company0" +
      "\001\022\"\n\003Ask\022\r.StockRequest\032\n.SellOrder0\001\022!\n" +
      "\003Bid\022\r.StockRequest\032\t.BuyOrder0\001\022&\n\005Orde" +
      "r\022\r.OrderRequest\032\016.OrderResponse\022=\n\014trad" +
      "eHistory\022\024.TradeHistoryRequest\032\025.TradeHi" +
      "storyResponse0\001B\024\n\020org.example.grpcP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { "Nesto", });
    internal_static_Company_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Company_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Company_descriptor,
        new java.lang.String[] { "Symbol", "CompanyName", "PriceNow", "PriceMorning", "Change", "Date", });
    internal_static_StockRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockRequest_descriptor,
        new java.lang.String[] { "Symbol", "Quantity", });
    internal_static_SellOrder_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SellOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SellOrder_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", });
    internal_static_BuyOrder_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_BuyOrder_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuyOrder_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "IdClient", "Ask", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new java.lang.String[] { "Response", });
    internal_static_TradeHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_TradeHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeHistoryRequest_descriptor,
        new java.lang.String[] { "Symbol", "Date", });
    internal_static_TradeHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_TradeHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeHistoryResponse_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "Timestamp", "BuyOrSell", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
