// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public interface TradeHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TradeHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>.google.protobuf.Timestamp date = 2;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 2;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();
}
