// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockEx.proto

package org.example.grpc;

public interface TradeHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TradeHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string symbol = 1;</code>
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 1;</code>
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>double price = 2;</code>
   */
  double getPrice();

  /**
   * <code>int32 quantity = 3;</code>
   */
  int getQuantity();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>bool buyOrSell = 5;</code>
   */
  boolean getBuyOrSell();
}
